apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: week1-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /protected
            pathType: Prefix
            backend:
              service:
                name: week1-api
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: week1-web
                port:
                  number: 80
