apiVersion: apps/v1
kind: Deployment
metadata:
  name: week1-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: week1-web
  template:
    metadata:
      labels:
        app: week1-web
    spec:
      imagePullSecrets:
        - name: acr-secret   
      containers:
        - name: week1-web
          image: mindxweek1acr123.azurecr.io/week1-web:clean
          ports:
            - containerPort: 80
